from __future__ import annotations

from app.schemas import AgentSkillDefinition


_SKILLS: list[AgentSkillDefinition] = [
    AgentSkillDefinition(
        skillId="read_runtime",
        category="read",
        label="Read Runtime",
        description="读取当前实验的 runtime、阶段机、日志和模型耗时。",
        requiredInputs=["experiment.runtime"],
        expectedDuration="<2s",
    ),
    AgentSkillDefinition(
        skillId="read_feature_factory",
        category="read",
        label="Read Feature Factory",
        description="读取 Feature Factory、Feature Flow、machines 与 selection 快照。",
        requiredInputs=["experiment.runtime.featurePipeline"],
        expectedDuration="<2s",
    ),
    AgentSkillDefinition(
        skillId="read_explainability",
        category="read",
        label="Read Explainability",
        description="读取 Feature Importance、SHAP 和推荐单点解释。",
        requiredInputs=["experiment.explainability"],
        expectedDuration="<2s",
    ),
    AgentSkillDefinition(
        skillId="read_residual_diagnostics",
        category="read",
        label="Read Residual Diagnostics",
        description="读取 backtest residual、异常点和误差模式。",
        requiredInputs=["experiment.backtest"],
        expectedDuration="<2s",
    ),
    AgentSkillDefinition(
        skillId="read_covariate_flow",
        category="read",
        label="Read Covariate Flow",
        description="读取 covariate 类型、策略和泄漏风险。",
        requiredInputs=["experiment.runtime.featurePipeline.covariates"],
        expectedDuration="<2s",
    ),
    AgentSkillDefinition(
        skillId="read_manifest",
        category="read",
        label="Read Manifest",
        description="读取 manifest、配置 hash、环境信息和复现实验元数据。",
        requiredInputs=["experiment.manifest"],
        expectedDuration="<2s",
    ),
    AgentSkillDefinition(
        skillId="read_report",
        category="read",
        label="Read Report",
        description="读取当前实验已有 AI 报告和关键结论片段。",
        requiredInputs=["experiment.reports"],
        expectedDuration="<2s",
    ),
    AgentSkillDefinition(
        skillId="read_existing_visual",
        category="read",
        label="Read Existing Visual",
        description="读取实验已有图表类型和可解释的视觉对象。",
        requiredInputs=["experiment.backtest", "experiment.finalForecast"],
        expectedDuration="<2s",
    ),
    AgentSkillDefinition(
        skillId="read_attribution_snapshot",
        category="read",
        label="Read Attribution Snapshot",
        description="读取当前归因实验室的 overview、quick diagnosis 和 scenario 摘要。",
        requiredInputs=["experiment.attribution"],
        expectedDuration="<2s",
    ),
    AgentSkillDefinition(
        skillId="anomaly_detection_zscore",
        category="analysis",
        label="Z-score Anomaly",
        description="基于序列或 residual 做 z-score 异常检测。",
        requiredInputs=["experiment.series", "experiment.backtest"],
        expectedDuration="2-5s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="yoy_mom_anomaly_check",
        category="analysis",
        label="YoY / MoM Check",
        description="做 period-over-period 变化诊断，优先给出同比/环比异常。",
        requiredInputs=["experiment.series"],
        expectedDuration="2-5s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="seasonality_normalization",
        category="analysis",
        label="Seasonality Normalization",
        description="按 weekday/month 归一后查看异常是否仍然成立。",
        requiredInputs=["experiment.series"],
        expectedDuration="2-5s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="driver_ranking",
        category="analysis",
        label="Driver Ranking",
        description="综合 explainability、covariate flow 和 residual，生成主要驱动候选排序。",
        requiredInputs=["experiment.explainability", "experiment.runtime.featurePipeline"],
        expectedDuration="2-5s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="hierarchical_drilldown",
        category="analysis",
        label="Hierarchical Drilldown",
        description="根据可用字段给出分层下钻建议或可执行的 drilldown 线索。",
        requiredInputs=["experiment.dataProfile"],
        expectedDuration="2-5s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="control_variable_view",
        category="analysis",
        label="Control Variable View",
        description="从协变量类型、策略和泄漏风险视角总结控制变量视图。",
        requiredInputs=["experiment.runtime.featurePipeline.covariates"],
        expectedDuration="2-5s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="tree_driver_analysis",
        category="analysis",
        label="Tree Driver Analysis",
        description="优先读取树模型 explainability，给出基于重要性/SHAP 的驱动解释。",
        requiredInputs=["experiment.explainability"],
        expectedDuration="2-5s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="regression_attribution",
        category="analysis",
        label="Regression Attribution",
        description="给出回归归因的 best-effort 解释，必要时明确指出缺少持久化特征矩阵。",
        requiredInputs=["experiment.series", "experiment.runtime.featurePipeline"],
        expectedDuration="3-8s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="sensitivity_analysis",
        category="analysis",
        label="Sensitivity Analysis",
        description="基于当前驱动排序生成敏感性分析摘要。",
        requiredInputs=["experiment.explainability", "experiment.finalForecast"],
        expectedDuration="3-8s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="elasticity_analysis",
        category="analysis",
        label="Elasticity Analysis",
        description="针对价格/促销等特征做弹性解释的 best-effort 分析。",
        requiredInputs=["experiment.explainability"],
        expectedDuration="3-8s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="benchmark_gap_analysis",
        category="analysis",
        label="Benchmark Gap Analysis",
        description="比较推荐模型和基线/第二名的差距与代价。",
        requiredInputs=["experiment.rankedModels"],
        expectedDuration="2-5s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="image_insight_caption",
        category="analysis",
        label="Image Insight Caption",
        description="对 Agent 生成的图表 artifact 做图像级说明与管理层 caption。",
        requiredInputs=["agent.artifacts"],
        expectedDuration="2-5s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="executive_summary_writeback",
        category="analysis",
        label="Executive Summary",
        description="把当前归因证据整理成管理层可读摘要。",
        requiredInputs=["agent.plan", "agent.artifacts"],
        expectedDuration="2-5s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="generate_waterfall_chart",
        category="action",
        label="Generate Waterfall",
        description="生成归因瀑布图 artifact。",
        requiredInputs=["driver_ranking"],
        sideEffects=["create_artifact"],
        expectedDuration="3-8s",
        supportsStreaming=True,
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="generate_heatmap",
        category="action",
        label="Generate Heatmap",
        description="生成异常/残差热力图 artifact。",
        requiredInputs=["anomaly_detection_zscore", "seasonality_normalization"],
        sideEffects=["create_artifact"],
        expectedDuration="3-8s",
        supportsStreaming=True,
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="generate_bubble_chart",
        category="action",
        label="Generate Bubble",
        description="生成模型对比或 driver bubble chart artifact。",
        requiredInputs=["benchmark_gap_analysis"],
        sideEffects=["create_artifact"],
        expectedDuration="3-8s",
        supportsStreaming=True,
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="generate_report_section",
        category="action",
        label="Generate Report Section",
        description="生成可直接复制到报告里的 markdown 章节。",
        requiredInputs=["agent.artifacts"],
        sideEffects=["create_artifact"],
        expectedDuration="2-5s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="generate_full_report",
        category="action",
        label="Generate Full Report",
        description="生成一份新的归因报告记录，不覆盖现有历史。",
        requiredInputs=["experiment", "agent.artifacts"],
        sideEffects=["create_report_record"],
        costLevel="medium",
        expectedDuration="5-20s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="run_scenario_analysis",
        category="action",
        label="Run Scenario Analysis",
        description="基于当前预测和误差分布生成上/下行情景。",
        requiredInputs=["experiment.finalForecast", "experiment.backtest"],
        sideEffects=["create_artifact"],
        costLevel="medium",
        expectedDuration="5-20s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="run_monte_carlo",
        category="action",
        label="Run Monte Carlo",
        description="基于残差波动生成 Monte Carlo 概率分布。",
        requiredInputs=["experiment.backtest", "experiment.finalForecast"],
        sideEffects=["create_artifact"],
        costLevel="medium",
        expectedDuration="5-20s",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="rerun_backtest_with_config",
        category="action",
        label="Rerun Backtest",
        description="尝试基于当前实验上下文发起新的 backtest；若上下文不足，给出受限说明。",
        requiredInputs=["experiment.config", "source_context"],
        sideEffects=["create_artifact", "may_start_runtime"],
        costLevel="high",
        expectedDuration="20s+",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="rerun_model_subset",
        category="action",
        label="Rerun Model Subset",
        description="尝试只重跑部分模型；若历史上下文不足，生成可执行建议而不是假执行。",
        requiredInputs=["experiment.config", "source_context"],
        sideEffects=["create_artifact", "may_start_runtime"],
        costLevel="high",
        expectedDuration="20s+",
        producesArtifacts=True,
    ),
    AgentSkillDefinition(
        skillId="rerun_covariate_strategy_experiment",
        category="action",
        label="Rerun Covariate Strategy",
        description="尝试比较不同 covariate backtest 策略；若缺少源上下文则生成策略实验卡片。",
        requiredInputs=["experiment.config", "source_context"],
        sideEffects=["create_artifact", "may_start_runtime"],
        costLevel="high",
        expectedDuration="20s+",
        producesArtifacts=True,
    ),
]


SKILL_REGISTRY = {skill.skillId: skill for skill in _SKILLS}


def list_available_agent_skills() -> list[AgentSkillDefinition]:
    return [skill.model_copy(deep=True) for skill in _SKILLS]


def get_skill_definition(skill_id: str) -> AgentSkillDefinition:
    return SKILL_REGISTRY[skill_id].model_copy(deep=True)
