DEFAULT_RANDOM_SEED = 42
APP_VERSION = "0.4.0"
EXPERIMENT_MANIFEST_SCHEMA_VERSION = "0.4"
FEATURE_PIPELINE_VERSION = "0.4"
RUNTIME_EVENT_SCHEMA_VERSION = "0.4"
BENCHMARK_RESULT_SCHEMA_VERSION = "0.4"
